### ISSUE TITLE
[roadmap/helm-overrides] Image can be too large 

### ISSUE THREAD

**Issue by tschale** [unikubehq/docs#23]
Seen on https://unikube.io/docs/roadmap/helm-overrides.html
Image can overflow when browser window isn't large enough (horizontal scroll necessary):
![image](https://user-images.githubusercontent.com/5681839/132810143-b0aff760-355b-4a33-a978-53367bfadb10.png)

**Comment by tschale** [comment]
Also seems to be different when accessing the site from the menu on the side (image is as wide as the text) and when reloading (image is wider than the text).

**Comment by tobifroe** [comment]
@tschale This should be fixed. Can you double check? You might have to clear your cache in order to get an up to date version.

**Comment by tschale** [comment]
Looks good, nice!
